sensor:
  - platform: dht
    model: AUTO_DETECT
    temperature:
        id: "temperatur"
        name: "Sensor dht Temperature"
        icon: "mdi:thermometer-lines"
        device_class: "temperature"
        state_class: "measurement"
        filters:
          - offset: -2.0
    humidity:
        name: "Sensor dht Humidity"
        icon: "mdi:water-percent"
    update_interval: 60s
    pin:
      number: GPIO16