substitutions:
  name: jonas #My not be longer then 10 letters
  ssid: !secret ssid
  ssid_pass: !secret ssid_pass
  webserver_user: !secret webserver_user
  webserver_pass: !secret webserver_pass
  fallback_pass: !secret fallback_pass
  #static_ip: 10.130.1.21
  #gateway: 10.130.1.1
  #subnet: 255.255.255.0

# Basic configuration for an ESP32 device
esphome:
  name: ${name}
  friendly_name: ${name}

# Hardware configuration
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:
  platform: esphome


wifi:
  ssid:  ${ssid}
  password: ${ssid_pass}

  ap:
    ssid: ESPHome ${name}
    password: ${fallback_pass}
captive_portal:



# Enable logging
logger:
  level: DEBUG
  #level: VERBOSE



web_server:
  port: 80
  auth:
    username: ${webserver_user}
    password: ${webserver_pass}

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Zurich
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org


# I2C Config
i2c:
  #ESP8266
  #sda: 4
  #scl: 5
  #ESP32
  sda: 21
  scl: 22
  scan: True
  id: bus_a



packages:
  # Include the remote receiver configuration
  ir:  !include ir_remote_receiver.yaml
  # Include the DHT sensor configuration
  dht: !include dht.yaml
  # Include the BMP280 sensor configuration
  #bmp280: !include bmp280.yaml
  # Include the ADC sensor configuration
  adc: !include adc.yaml
  # Include the TM1637 display configuration
  tm1637: !include tm1637.yaml
  # Include the WiFi signal sensor configuration
  wifi_signal: !include wifi_signal.yaml
  # Include the buzzers configuration
  rtttl: !include buzzer.yaml
  # Include the button configuration
  button: !include button.yaml
  # Include the LED configuration
  led: !include led.yaml
  # Include the select configuration
  select: !include select.yaml
  # Include the startup configuration
  startup: !include startup.yaml
  #Include the LCD Display configuration
  #lcd: !include lcd_pcf8574.yaml







